[project]
name = "chameleon-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "typer>=0.15.1",
    "niquests>=3.12.1",
    "fastapi>=0.115.6",
    "uvicorn>=0.34.0",
]


[tool.pdm]

