[project]
name = "chameleon-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.6",
    "uvicorn>=0.34.0",
    "bokeh>=3.6.3",
    "numpy>=2.2.2",
]


[tool.pdm]

